[tools]
cmake = "4.3.1"
conan = "2.27.0"
ninja = "1.13.2"

[tasks.conan-install]
description = "Instala dependencias com Conan"
run = "conan install . --build=missing -s build_type=Release"

[tasks.configure]
description = "Configura o projeto CMake"
depends = ["conan-install"]
run = "cmake --preset conan-release"

[tasks.build]
description = "Compila o projeto"
depends = ["configure"]
run = "cmake --build --preset conan-release"
